#!/bin/sh -e

MAILTO=root
PIPE=/var/log/socklog/.notify

if [ ! -p "$PIPE" ]; then mkfifo -m0620 "$PIPE"; fi
chown log:adm "$PIPE"

exec < "$PIPE"
exec setuidgid log uncat -s49999 -t180 \
  env QMAILUSER=log QMAILNAME='socklog notify' \
  sh -c "mailsubj socklog-notify $MAILTO"
