#!/bin/sh -e

MAILTO=root
PIPE=/var/log/socklog/.notify

if [ ! -p "$PIPE" ]; then mknod "$PIPE" p; fi
chmod 666 "$PIPE"

exec < "$PIPE"
exec setuidgid log uncat -s49999 -t180 \
  env QMAILUSER=log QMAILNAME='socklog notify' \
  sh -c "mailsubj socklog-notify $MAILTO"
