#!/bin/sh
LOGDIR=/var/log/socklog-remote
exec setuidgid log multilog ${LOGDIR}/main \
	-* +kern.* ${LOGDIR}/kern \
	-* +user.* ${LOGDIR}/user \
	-* +mail.* ${LOGDIR}/mail \
	-* +daemon.* ${LOGDIR}/daemon \
	-* +auth.* ${LOGDIR}/auth \
	-* +syslog.* ${LOGDIR}/syslog \
	-* +lpr.* ${LOGDIR}/lpr \
	-* +news.* ${LOGDIR}/news \
	-* +uucp.* ${LOGDIR}/uucp \
	-* +cron.* ${LOGDIR}/cron \
	-* +authpriv.* ${LOGDIR}/authpriv \
	-* +ftp.* ${LOGDIR}/ftp \
	-* +local*.* ${LOGDIR}/local \
	-* +*.debug* ${LOGDIR}/debug
