#!/bin/sh
LOGDIR=/var/log/socklog-remote
exec setuidgid log multilog ${LOGDIR}/main \
  -* +kern.* ${LOGDIR}/kern \
  -* +user.* ${LOGDIR}/user \
  -* +mail.* ${LOGDIR}/mail \
  -* +daemon.* ${LOGDIR}/daemon \
  -* +auth.* +authpriv.* ${LOGDIR}/auth \
  -* +syslog.* ${LOGDIR}/syslog \
  -* +news.* ${LOGDIR}/news \
  -* +cron.* ${LOGDIR}/cron \
  -* +ftp.* ${LOGDIR}/ftp \
  -* +local*.* ${LOGDIR}/local \
  -* +*.debug* ${LOGDIR}/debug
