#!/bin/sh
LOGDIR=/var/log/socklog-remote
exec setuidgid log multilog t ${LOGDIR}/main

# not reached

# use something like this to seperate logs with timestamps by machine or
# network
exec setuidgid log multilog t ${LOGDIR}/main \
  s4999999 n10 -* +'* 10.0.0.2:' ${LOGDIR}/10.0.0.2 \
  s4999999 n10 -* +'* 10.1.0.*:' ${LOGDIR}/10.1.0
            
# use something like this to seperate logs without timestamps by
# facility.priority
exec setuidgid log multilog ${LOGDIR}/main \
  -* +kern.* ${LOGDIR}/kern \
  -* +user.* ${LOGDIR}/user \
  -* +mail.* ${LOGDIR}/mail \
  -* +daemon.* ${LOGDIR}/daemon \
  -* +auth.* +authpriv.* ${LOGDIR}/auth \
  -* +syslog.* ${LOGDIR}/syslog \
  -* +news.* ${LOGDIR}/news \
  -* +cron.* ${LOGDIR}/cron \
  -* +ftp.* ${LOGDIR}/ftp \
  -* +local*.* ${LOGDIR}/local \
  -* +*.debug* ${LOGDIR}/debug
